version: "3"

services:
  front:
    image: react-front
    container_name: react-front
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - a305-net

networks:
    a305-net:
        external:
            name: a305-net