version: "3"
services:
  front:
    image: wx776654/a305:react-front
    container_name: react-front
    ports:
      - 3000:3000
    restart: always
    networks:
      - a305-net
networks:
  a305-net:
    external:
      name: a305-net