version: "3"

services:
  frontend:
    image: react-front:latest
    container_name: react-front
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always