version: "3.7"

services:
  react-front:
    container_name: react-front
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - a305-net
networks:
  a305-net:
    external:
      name: a305-net