spring:
    config:
      activate:
          on-profile: prod
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://j8a305.p.ssafy.io:3371/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: false
                format_sql: true

server:
    port: 8007
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
cloud:
    gcp:
        storage:
            bucket: mpoffice
            project-id: robust-metrics-38060
            credentials:
                location: classpath:robust-metrics-380604-8e932ce5312a.json
