spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: ${HOST}
#        username: ${USERNAME}
#        password: ${PASSWORD}
        url: jdbc:mysql://j8a305.p.ssafy.io:3071/mpoffice-project?serverTimezone=Asia/Seoul
        username: a305
        password: dkanakf156346!!

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: false
                format_sql: true

        open-in-view: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    redis:
        port:
            6379
        host:
            https://j8a305.p.ssafy.io


server:
    port: 8071
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
cloud:
    gcp:
        storage:
            bucket: mpoffice
            project-id: robust-metrics-38060
            credentials:
                location: classpath:robust-metrics-380604-8e932ce5312a.json

app:
    business:
        url: https://j8a305.p.ssafy.io/api/auction
    cors:
        allowedOrigins: http://localhost:3000
    auth:
        token-expiration-msec: 864000000
        token-secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1

