server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e0354562c9e02eb4e7c321aa7515168c
            client-secret: 8iGdFxRFi25azwpMEJ4D1o1gyLWDjrIq
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: https://j8a305.p.ssafy.io/api/auth/oauth2/callback/kakao
#            redirect-uri: http://localhost:8070/api/auth/oauth2/callback/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  server:
    user: https://j8a305.p.ssafy.io/api/mpoffice

  auth:
    token-expiration-msec: 864000000
    token-secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1

  oauth2:
    authorized-redirect-uris: https://j8a305.p.ssafy.io/oauth2/redirect, http://localhost:3000/oauth2/redirect, http://j8a305.p.ssafy.io:3000/oauth2/redirect
#    authorized-redirect-uris: http://localhost:3000/oauth2/redirect


